name: action-body-fields
description: Add fields to github PR body
author: insidewhy
runs:
  using: node20
  main: lib/index.js
branding:
  icon: check-square
  color: blue
inputs:
  fields:
    description: 'Fields to prepend, one per line in format "key: value"'
  github-token:
    description: Github token used for amending body
    default: ${{ github.token }}
  issue-number:
    description: Issue id to attach comment to
    default: ${{ github.event.number }}
  repository:
    description: The github repository in the form ${organisation}/${repository}
    default: ${{ github.repository }}
  prepend:
    description: Prepend new fields
    required: false
  append-to-values:
    description: Append the values to each value when not already present instead of replacing them
  title:
    description: Update title to specified string
  title-from:
    description: Update issue title from named field
  remove-fields:
    description: Remove comma separated list of fields
  header:
    description: Add a header to the block
  footer:
    description: Add a footer to the block
